In [1]:
import numpy as np

In [2]:
numbers = [1,2,3,4,5]

np.mean(numbers)

3.0

In [4]:
np.linspace(-3,3,100)

array([-3.        , -2.93939394, -2.87878788, -2.81818182, -2.75757576,
       -2.6969697 , -2.63636364, -2.57575758, -2.51515152, -2.45454545,
       -2.39393939, -2.33333333, -2.27272727, -2.21212121, -2.15151515,
       -2.09090909, -2.03030303, -1.96969697, -1.90909091, -1.84848485,
       -1.78787879, -1.72727273, -1.66666667, -1.60606061, -1.54545455,
       -1.48484848, -1.42424242, -1.36363636, -1.3030303 , -1.24242424,
       -1.18181818, -1.12121212, -1.06060606, -1.        , -0.93939394,
       -0.87878788, -0.81818182, -0.75757576, -0.6969697 , -0.63636364,
       -0.57575758, -0.51515152, -0.45454545, -0.39393939, -0.33333333,
       -0.27272727, -0.21212121, -0.15151515, -0.09090909, -0.03030303,
        0.03030303,  0.09090909,  0.15151515,  0.21212121,  0.27272727,
        0.33333333,  0.39393939,  0.45454545,  0.51515152,  0.57575758,
        0.63636364,  0.6969697 ,  0.75757576,  0.81818182,  0.87878788,
        0.93939394,  1.        ,  1.06060606,  1.12121212,  1.18

In [5]:
numbers_np = np.array(numbers)

print(type(numbers))
print(type(numbers_np))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
numbers

[1, 2, 3, 4, 5]

In [6]:
numbers_np.mean()

3.0

In [7]:
numbers_np.min()

1

In [8]:
numbers_np.max()

5

## Inplace/Out-of-place operations

In [9]:
n = [4,5,9,0,11,5,6,7]
nn = np.array(n)

print(n)
n.sort()
print(n)

[4, 5, 9, 0, 11, 5, 6, 7]
[0, 4, 5, 5, 6, 7, 9, 11]


In [11]:
n = [4,5,9,0,11,5,6,7]
nn = np.array(n)

print(nn)
nn = np.sort(nn)
print(nn)

[ 4  5  9  0 11  5  6  7]
[ 0  4  5  5  6  7  9 11]


In [12]:
np.sort??

Signature: np.sort(a, axis=-1, kind=None, order=None)
Source:   
@array_function_dispatch(_sort_dispatcher)
def sort(a, axis=-1, kind=None, order=None):
    """
    Return a sorted copy of an array.

    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.

        .. versionchanged:: 1.15.0.
           The 'stable' option was added.

    order : str or list of str, optional
        When `a` is an array with fields defined, this argumen